version: '3.8'
services:
  os-service:
    image: os-service:0.0.1
    build:
      context: ./os-service
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    networks:
      - local-network

networks:
  local-network:
    external: true
