version: "3.8"
services:
  dcs-postgres-os:
    image: postgres:15.3-alpine
    container_name: dcs-postgres-os
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5434:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data